name: Deploy Docker image to AWS

on:
  workflow_run:
    workflows: ["Publish Docker Image"]
    types: [completed]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Stop the old container
        run: docker stop demo-server-container || true

      - name: Delete the old container
        run: docker rm demo-server-container || true

      - name: Delete the old image
        run: docker rmi ${{secrets.DOCKERHUB_USERNAME}}/demo-server:latest || true

      - name: Pull the image from dockerhub
        run: docker pull ${{secrets.DOCKERHUB_USERNAME}}/demo-server:latest

      - name: Run the image
        run: docker compose up -d
